-- Create tables
CREATE TABLE IF NOT EXISTS authors (
    id SERIAL PRIMARY KEY,
    "firstName" VARCHAR(100) NOT NULL,
    "lastName" VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    bio TEXT,
    country VARCHAR(100),
    "birthDate" DATE,
    "isActive" BOOLEAN DEFAULT TRUE,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(100),
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    "isPublished" BOOLEAN DEFAULT TRUE,
    "publishedDate" DATE,
    tags TEXT,
    "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "authorId" INTEGER NOT NULL,
    FOREIGN KEY ("authorId") REFERENCES authors(id) ON DELETE CASCADE
);

-- Insert 50 Authors
INSERT INTO authors ("firstName", "lastName", email, bio, country, "birthDate", "isActive") VALUES
('John', 'Doe', 'john.doe@example.com', 'Passionate tech writer with 10 years of experience in software development.', 'USA', '1985-03-15', TRUE),
('Jane', 'Smith', 'jane.smith@example.com', 'Award-winning journalist covering technology and innovation.', 'UK', '1990-07-22', TRUE),
('Carlos', 'García', 'carlos.garcia@example.com', 'Colombian developer and blogger specializing in web technologies.', 'Colombia', '1988-11-30', TRUE),
('Maria', 'Rodriguez', 'maria.rodriguez@example.com', 'Full-stack developer and technical writer.', 'Spain', '1992-05-18', TRUE),
('Ahmed', 'Hassan', 'ahmed.hassan@example.com', 'Software architect with expertise in distributed systems.', 'Egypt', '1987-09-25', TRUE),
('Sophie', 'Martin', 'sophie.martin@example.com', 'UX designer and content creator focused on user experience.', 'France', '1991-12-10', TRUE),
('David', 'Kim', 'david.kim@example.com', 'Machine learning engineer and AI researcher.', 'South Korea', '1989-04-08', TRUE),
('Emma', 'Brown', 'emma.brown@example.com', 'Front-end developer passionate about modern web frameworks.', 'Australia', '1993-02-14', TRUE),
('Lucas', 'Silva', 'lucas.silva@example.com', 'Backend developer specializing in microservices architecture.', 'Brazil', '1986-08-20', TRUE),
('Anna', 'Kowalski', 'anna.kowalski@example.com', 'DevOps engineer and cloud computing specialist.', 'Poland', '1990-06-05', TRUE),
('Mohammed', 'Ali', 'mohammed.ali@example.com', 'Cybersecurity expert and ethical hacker.', 'UAE', '1988-10-12', TRUE),
('Lisa', 'Johnson', 'lisa.johnson@example.com', 'Mobile app developer with focus on iOS and Android.', 'Canada', '1991-03-28', TRUE),
('Pierre', 'Dubois', 'pierre.dubois@example.com', 'Data scientist and analytics consultant.', 'Belgium', '1987-07-16', TRUE),
('Yuki', 'Tanaka', 'yuki.tanaka@example.com', 'Game developer and 3D graphics programmer.', 'Japan', '1992-01-09', TRUE),
('Isabella', 'Rossi', 'isabella.rossi@example.com', 'Technical writer documenting open-source projects.', 'Italy', '1989-11-23', TRUE),
('Hans', 'Mueller', 'hans.mueller@example.com', 'Embedded systems engineer and IoT specialist.', 'Germany', '1985-04-30', TRUE),
('Priya', 'Sharma', 'priya.sharma@example.com', 'Cloud architect designing scalable solutions.', 'India', '1990-09-17', TRUE),
('Oscar', 'Fernandez', 'oscar.fernandez@example.com', 'Blockchain developer and cryptocurrency enthusiast.', 'Mexico', '1988-12-25', TRUE),
('Emily', 'Taylor', 'emily.taylor@example.com', 'QA engineer focused on automated testing.', 'New Zealand', '1993-05-11', TRUE),
('Viktor', 'Petrov', 'viktor.petrov@example.com', 'Systems administrator and Linux expert.', 'Russia', '1986-02-28', TRUE),
('Fatima', 'Khan', 'fatima.khan@example.com', 'Product manager with technical background.', 'Pakistan', '1991-08-07', TRUE),
('Thomas', 'Anderson', 'thomas.anderson@example.com', 'Database administrator specializing in PostgreSQL.', 'Sweden', '1987-10-19', TRUE),
('Olivia', 'Wilson', 'olivia.wilson@example.com', 'Full-stack JavaScript developer.', 'Ireland', '1992-06-14', TRUE),
('Diego', 'Lopez', 'diego.lopez@example.com', 'Software engineer building enterprise applications.', 'Argentina', '1989-03-22', TRUE),
('Aisha', 'Mohamed', 'aisha.mohamed@example.com', 'AI researcher working on natural language processing.', 'Morocco', '1990-07-08', TRUE),
('Sebastian', 'Wagner', 'sebastian.wagner@example.com', 'Performance optimization specialist.', 'Austria', '1988-11-15', TRUE),
('Chloe', 'Leclerc', 'chloe.leclerc@example.com', 'Agile coach and scrum master.', 'Switzerland', '1991-01-26', TRUE),
('Raj', 'Patel', 'raj.patel@example.com', 'Software consultant and architecture expert.', 'India', '1986-09-03', TRUE),
('Nina', 'Sokolova', 'nina.sokolova@example.com', 'Computer vision engineer.', 'Ukraine', '1992-04-17', TRUE),
('Miguel', 'Santos', 'miguel.santos@example.com', 'API developer and microservices advocate.', 'Portugal', '1987-12-29', TRUE),
('Sarah', 'Lee', 'sarah.lee@example.com', 'Technical team lead with 15 years experience.', 'Singapore', '1985-05-21', TRUE),
('Fredrik', 'Larsson', 'fredrik.larsson@example.com', 'Open-source contributor and community manager.', 'Norway', '1990-08-13', TRUE),
('Gabriela', 'Costa', 'gabriela.costa@example.com', 'Software tester and quality advocate.', 'Chile', '1991-02-06', TRUE),
('Ali', 'Yilmaz', 'ali.yilmaz@example.com', 'Full-stack developer with Ruby expertise.', 'Turkey', '1988-06-24', TRUE),
('Natalie', 'Bergman', 'natalie.bergman@example.com', 'UX researcher and usability specialist.', 'Denmark', '1993-10-10', TRUE),
('Roberto', 'Bianchi', 'roberto.bianchi@example.com', 'Infrastructure engineer and Kubernetes expert.', 'Italy', '1987-03-18', TRUE),
('Mei', 'Chen', 'mei.chen@example.com', 'Mobile UI designer and Flutter developer.', 'China', '1991-07-31', TRUE),
('Jonas', 'Eriksson', 'jonas.eriksson@example.com', 'Security architect and penetration tester.', 'Finland', '1989-01-14', TRUE),
('Valentina', 'Ivanova', 'valentina.ivanova@example.com', 'Tech blogger and conference speaker.', 'Bulgaria', '1992-09-27', TRUE),
('Marco', 'Ricci', 'marco.ricci@example.com', 'Distributed systems engineer.', 'Italy', '1986-11-08', TRUE),
('Amira', 'Nasser', 'amira.nasser@example.com', 'Software developer passionate about clean code.', 'Lebanon', '1990-04-19', TRUE),
('Lars', 'Hansen', 'lars.hansen@example.com', 'Backend developer specializing in Python and Go.', 'Netherlands', '1988-08-02', TRUE),
('Camila', 'Torres', 'camila.torres@example.com', 'JavaScript developer and React specialist.', 'Colombia', '1991-12-15', TRUE),
('Dimitri', 'Volkov', 'dimitri.volkov@example.com', 'Robotics engineer and automation expert.', 'Russia', '1987-05-28', TRUE),
('Jasmine', 'Wong', 'jasmine.wong@example.com', 'Technical writer documenting APIs and SDKs.', 'Malaysia', '1992-02-11', TRUE),
('Andrei', 'Popescu', 'andrei.popescu@example.com', 'Game developer working with Unity and Unreal Engine.', 'Romania', '1989-06-23', TRUE),
('Sofia', 'Gutierrez', 'sofia.gutierrez@example.com', 'Cloud engineer specializing in AWS and Azure.', 'Venezuela', '1990-10-05', TRUE),
('Klaus', 'Schmidt', 'klaus.schmidt@example.com', 'Senior developer with expertise in C++ and Java.', 'Germany', '1985-07-12', TRUE),
('Layla', 'Abdullah', 'layla.abdullah@example.com', 'Web developer focused on accessibility and performance.', 'Saudi Arabia', '1991-03-09', TRUE),
('Matteo', 'Romano', 'matteo.romano@example.com', 'Software architect designing scalable web applications.', 'Italy', '1988-09-16', TRUE);

-- Insert 50 Posts
INSERT INTO posts (title, content, category, views, likes, "isPublished", "publishedDate", tags, "authorId") VALUES
('Getting Started with TypeScript', 'TypeScript has become an essential tool for modern JavaScript development. In this comprehensive guide, we will explore the fundamentals of TypeScript and how it can improve your development workflow.', 'Programming', 1250, 89, TRUE, '2024-01-15', 'typescript,javascript,programming', 1),
('The Future of Web Development', 'As we move into 2024, web development continues to evolve at a rapid pace. Let us explore the emerging trends and technologies that are shaping the future of the web.', 'Technology', 2340, 156, TRUE, '2024-02-20', 'web,development,trends', 2),
('Building Scalable Microservices', 'Microservices architecture has revolutionized how we build and deploy applications. This article covers best practices for designing scalable microservice systems.', 'Architecture', 1890, 124, TRUE, '2024-01-28', 'microservices,architecture,scalability', 3),
('React Hooks Deep Dive', 'React Hooks have transformed how we write React components. Learn advanced patterns and best practices for using hooks effectively in your applications.', 'Frontend', 3200, 245, TRUE, '2024-03-05', 'react,hooks,javascript', 4),
('Machine Learning Basics', 'An introduction to machine learning concepts and algorithms. Perfect for developers looking to get started with ML and AI technologies.', 'AI/ML', 2100, 178, TRUE, '2024-02-10', 'machine-learning,ai,data-science', 7),
('CSS Grid vs Flexbox', 'Understanding when to use CSS Grid and when to use Flexbox is crucial for modern web layout design. This guide compares both approaches.', 'CSS', 1670, 98, TRUE, '2024-01-22', 'css,layout,design', 8),
('Docker Best Practices', 'Containerization with Docker has become standard practice. Learn the best practices for creating efficient and secure Docker containers.', 'DevOps', 2450, 189, TRUE, '2024-02-15', 'docker,containers,devops', 10),
('API Design Principles', 'Creating well-designed APIs is crucial for building maintainable systems. Explore the principles that make APIs intuitive and developer-friendly.', 'Backend', 1980, 142, TRUE, '2024-03-01', 'api,rest,design', 9),
('Introduction to GraphQL', 'GraphQL offers a powerful alternative to REST APIs. Discover how GraphQL can simplify your data fetching and improve client-server communication.', 'Backend', 2780, 201, TRUE, '2024-02-25', 'graphql,api,backend', 5),
('Cybersecurity in 2024', 'Security threats continue to evolve. Stay informed about the latest cybersecurity trends and how to protect your applications.', 'Security', 3100, 267, TRUE, '2024-03-10', 'security,cybersecurity,best-practices', 11),
('Mobile Development with Flutter', 'Flutter enables beautiful native apps from a single codebase. Learn how to get started with Flutter for mobile development.', 'Mobile', 2230, 165, TRUE, '2024-01-30', 'flutter,mobile,dart', 12),
('Data Science with Python', 'Python has become the language of choice for data science. Explore the essential libraries and tools for data analysis.', 'Data Science', 2890, 223, TRUE, '2024-02-18', 'python,data-science,analytics', 13),
('Game Development Fundamentals', 'Learn the core concepts of game development, from physics engines to rendering pipelines.', 'Gaming', 1560, 112, TRUE, '2024-01-25', 'gamedev,unity,programming', 14),
('Technical Writing Tips', 'Effective technical writing is a valuable skill. Discover techniques for creating clear and comprehensive documentation.', 'Writing', 1340, 87, TRUE, '2024-02-08', 'writing,documentation,communication', 15),
('IoT and Edge Computing', 'The Internet of Things is transforming industries. Explore how edge computing enables efficient IoT solutions.', 'IoT', 1890, 134, TRUE, '2024-03-03', 'iot,edge-computing,embedded', 16),
('Cloud Architecture Patterns', 'Designing cloud-native applications requires understanding key architectural patterns. Learn the patterns that enable scalable cloud systems.', 'Cloud', 2650, 198, TRUE, '2024-02-22', 'cloud,architecture,aws', 17),
('Blockchain for Developers', 'Blockchain technology extends beyond cryptocurrency. Discover how to build decentralized applications.', 'Blockchain', 2120, 156, TRUE, '2024-01-18', 'blockchain,web3,cryptocurrency', 18),
('Automated Testing Strategies', 'Quality assurance through automated testing saves time and catches bugs early. Learn effective testing strategies.', 'Testing', 1780, 119, TRUE, '2024-02-12', 'testing,qa,automation', 19),
('Linux System Administration', 'Master the essential skills for managing Linux servers and infrastructure.', 'Systems', 2340, 187, TRUE, '2024-03-07', 'linux,sysadmin,devops', 20),
('Product Management for Engineers', 'Technical product management combines engineering and business skills. Learn how to excel in this role.', 'Management', 1450, 95, TRUE, '2024-01-20', 'product,management,engineering', 21),
('PostgreSQL Performance Tuning', 'Optimize your PostgreSQL databases for maximum performance with these advanced techniques.', 'Database', 2560, 203, TRUE, '2024-02-28', 'postgresql,database,performance', 22),
('Modern JavaScript Patterns', 'JavaScript continues to evolve. Explore modern patterns and best practices for clean, maintainable code.', 'JavaScript', 2980, 234, TRUE, '2024-03-12', 'javascript,patterns,best-practices', 23),
('Building Enterprise Applications', 'Enterprise software requires robust architecture and careful planning. Learn the fundamentals of enterprise development.', 'Enterprise', 1670, 121, TRUE, '2024-01-27', 'enterprise,architecture,development', 24),
('Natural Language Processing', 'NLP is revolutionizing how computers understand human language. Dive into the fundamentals of NLP.', 'AI/ML', 2430, 189, TRUE, '2024-02-16', 'nlp,ai,machine-learning', 25),
('Performance Optimization Techniques', 'Speed matters. Learn how to identify and fix performance bottlenecks in your applications.', 'Performance', 2120, 167, TRUE, '2024-03-04', 'performance,optimization,speed', 26),
('Agile Development Practices', 'Agile methodologies improve team collaboration and project outcomes. Master agile practices for software development.', 'Methodology', 1890, 143, TRUE, '2024-02-05', 'agile,scrum,methodology', 27),
('Software Architecture Fundamentals', 'Good architecture is the foundation of maintainable software. Learn the principles of software architecture.', 'Architecture', 2340, 178, TRUE, '2024-01-23', 'architecture,design,patterns', 28),
('Computer Vision Applications', 'Computer vision is enabling new possibilities in AI. Explore practical applications and implementations.', 'AI/ML', 2670, 201, TRUE, '2024-02-27', 'computer-vision,ai,image-processing', 29),
('RESTful API Development', 'REST APIs are the backbone of modern web services. Learn how to design and implement robust REST APIs.', 'Backend', 3120, 245, TRUE, '2024-03-09', 'rest,api,web-services', 30),
('Leadership in Tech Teams', 'Technical leadership requires both technical and people skills. Develop your leadership abilities.', 'Leadership', 1780, 132, TRUE, '2024-02-11', 'leadership,management,teams', 31),
('Open Source Contribution Guide', 'Contributing to open source can boost your career and help the community. Learn how to get started.', 'Open Source', 2230, 176, TRUE, '2024-01-29', 'opensource,community,git', 32),
('Software Testing Best Practices', 'Quality software requires comprehensive testing. Master testing strategies and tools.', 'Testing', 1950, 148, TRUE, '2024-02-19', 'testing,quality,best-practices', 33),
('Ruby on Rails in 2024', 'Rails continues to be a productive framework for web development. Explore modern Rails development.', 'Backend', 1560, 103, TRUE, '2024-03-06', 'ruby,rails,web-development', 34),
('UX Research Methods', 'Understanding users is key to building great products. Learn effective UX research techniques.', 'UX/UI', 2010, 159, TRUE, '2024-02-13', 'ux,research,design', 35),
('Kubernetes Deployment Guide', 'Container orchestration with Kubernetes is essential for modern cloud infrastructure.', 'DevOps', 2890, 221, TRUE, '2024-01-26', 'kubernetes,devops,containers', 36),
('Flutter UI Design Patterns', 'Create beautiful and responsive UIs with Flutter. Learn essential design patterns and widgets.', 'Mobile', 2120, 168, TRUE, '2024-02-24', 'flutter,ui,mobile-design', 37),
('Application Security Testing', 'Security testing should be part of every development cycle. Learn penetration testing techniques.', 'Security', 2450, 193, TRUE, '2024-03-11', 'security,pentesting,appsec', 38),
('Tech Blogging Success', 'Build your personal brand through technical blogging. Tips for creating engaging technical content.', 'Writing', 1670, 124, TRUE, '2024-02-09', 'blogging,writing,content', 39),
('Distributed Systems Design', 'Distributed systems present unique challenges. Learn patterns for building reliable distributed applications.', 'Architecture', 2780, 215, TRUE, '2024-01-31', 'distributed-systems,architecture,scalability', 40),
('Clean Code Principles', 'Writing clean, maintainable code is a crucial skill. Master the principles of clean coding.', 'Programming', 3200, 267, TRUE, '2024-02-26', 'clean-code,best-practices,programming', 41),
('Python and Go Comparison', 'Both Python and Go have their strengths. Compare these popular backend languages.', 'Programming', 2340, 189, TRUE, '2024-03-08', 'python,golang,comparison', 42),
('React Component Libraries', 'Accelerate development with React component libraries. Overview of popular UI libraries.', 'Frontend', 1980, 152, TRUE, '2024-02-14', 'react,components,ui-libraries', 43),
('Robotics Programming Guide', 'Enter the world of robotics programming. Learn how to program robots and automation systems.', 'Robotics', 1560, 116, TRUE, '2024-01-24', 'robotics,automation,programming', 44),
('API Documentation Best Practices', 'Great documentation makes APIs easy to use. Learn how to create effective API documentation.', 'Documentation', 2010, 163, TRUE, '2024-02-21', 'documentation,api,technical-writing', 45),
('Unity Game Development', 'Unity is the leading game engine. Get started with Unity game development.', 'Gaming', 2450, 197, TRUE, '2024-03-02', 'unity,gamedev,3d', 46),
('Cloud Cost Optimization', 'Manage cloud costs effectively while maintaining performance. Strategies for cloud cost optimization.', 'Cloud', 2120, 171, TRUE, '2024-02-17', 'cloud,aws,azure,cost-optimization', 47),
('Java and C++ for Performance', 'When performance is critical, Java and C++ are top choices. Deep dive into performance programming.', 'Programming', 1890, 138, TRUE, '2024-01-21', 'java,cpp,performance', 48),
('Web Accessibility Guide', 'Building accessible websites is both ethical and practical. Learn accessibility best practices.', 'Web Development', 2340, 186, TRUE, '2024-02-23', 'accessibility,web,a11y', 49),
('Scalable Web Applications', 'Design web applications that can handle millions of users. Architecture patterns for scalability.', 'Architecture', 2890, 228, TRUE, '2024-03-13', 'scalability,architecture,web', 50);
